### ISSUE TITLE
Single NuGet package

### ISSUE THREAD

**Issue by eredmo** [mocklis/mocklis#1]
From off-line discussion with David H:

At the moment (0.1.13-alpha) you need to reference two NuGet packages to start working with Mocklis: ``Mocklis.Generator`` and either ``Mocklis.Core`` or something that references it. This reduces perceived ease-of-use, and while the chore of referencing another package is small it happens right in the crucial first few minutes of usage.

This issue would be remedied if there was a way to bring in ``Mocklis.Core``, ``Mocklis`` and ``Mocklis.Generator`` with a single package reference.

**Comment by eredmo** [comment]
What feels like the natural thing is to have ``Mocklis.MockGenerator`` reference ``Mocklis.Core`` - after all ``Mocklis.Core`` contains the bare minimum functionality required by the code created by the generator.

Technically however, ``Mocklis.MockGenerator`` is just looking for the existence of types with the right names, and there are a few perks with having them separate - it's possible to add source code for ``Mocklis`` and ``Mocklis.Core`` directly to your solution to fully debug mocks for instance.

But we could do it the other way around - let ``Mocklis.Core`` reference ``Mocklis.MockGenerator``.

Pros:
* You only have to reference one NuGet package; ``Mocklis.Core`` for mock-only projects and ``Mocklis`` for those that contain usage of the mock classes or just want to be on the safe side. Note that ``Mocklis`` references ``Mocklis.Core`` and is the natural thing to bring in given its name.
* If you want to import the source code you can still do this - you'd have to reference the mock generator separately in this case but if you've deliberately gone down this particular path I don't think you'd worry too much about that.
* There is no need to change what the different NuGet packages are for - which is a very good thing since I really don't want to re-purpose the 'top level' ``Mocklis`` package.
* It's a proven approach; xunit has referenced xunit.analyzers since version 2.3.0.

Cons:
* All projects with any ``Mocklis`` references would take a small performance hit by ``Mocklis.CodeGenerator`` inspecting the code looking for ``MocklisClass`` attributes.
* Any change to the generator would require a re-release of ``Mocklis.Core`` and ``Mocklis`` to make sure the latest version of the generator is used.
* I would have to re-write parts of the documentation, but that's probably not a bad thing anyway... :o]

**Comment by ninjasource** [comment]
Hi Esbjörn, 

I like the pros! About the cons:

>     * All projects with any `Mocklis` references would take a small performance hit by `Mocklis.CodeGenerator` inspecting the code looking for `MocklisClass` attributes.

How likely is it that someone would want to Mocklis but not Mocklis.CodeGenerator? Usually you have one unit test project for each assembly you want to test. Why would you not want to use CodeGenerator in that case?
