### ISSUE TITLE
Change dependency structure

### ISSUE THREAD

**Issue by eredmo** [mocklis/mocklis#15]
Currently Mocklis consists of five packages.

* Mocklis.MockGenerator does not depend on anything.
* Mocklis.Core does not depend on anything.
* Mocklis depends on Mocklis.Core and Mocklis.MockGenerator
* Mocklis.Serilog2 and Mocklis.Experimental both depend on Mocklis (and therefore also on Mocklis.Core and Mocklis.MockGenerator).

However Mocklis does not really depend on Mocklis.MockGenerator - it's only there so that a user can reference the Mocklis Nuget package and get everything he or she needs to start working.

The suggested change is to rename Mocklis to Mocklis.BaseApi, remove the dependency on Mocklis.MockGenerator from Mocklis, and repurpose the Mocklis nuget package to be a metapackage with references to Mocklis.BaseApi and Mocklis.MockGenerator.

This way anyone who references Mocklis doesn't see a change, but we gain more freedom in developing Mocklis.MockGenerator and the other packages independently.

**Comment by jales** [comment]
Careful with nuget package renames. 

Remember the tragedy that was the big rename of Reactive Extensions...

**Comment by eredmo** [comment]
Yes indeed, and thank you for the reminder.

The way the change is planned, there won't be a change for anyone who has referenced Mocklis, Mocklis.Core or Mocklis.MockGenerator in any combination, except that the Mocklis.dll will be renamed to Mocklis.BaseApi.dll. (Technically it could stay as Mocklis.dll but that will probably be more confusing as there will be a Mocklis project still for the meta package.)

If you only referenced Mocklis.Serilog2 or Mocklis.Experimental and relied on transitive references to get the rest you'll miss out on the Mocklis.MockGenerator after this change. However this is easy enough to add back in, and won't affect the compilation of any code if it's missing.

Having said all of that, I do understand the concern and some extra testing is definitely called for.
