### ISSUE TITLE
Lenient-by-default

### ISSUE THREAD

**Issue by eredmo** [mocklis/mocklis#2]
From off-line discussion with David H:

The current (0.1.13-alpha) was designed to force developers to make informed decisions on what to mock and how. If a given member of a ``MocklisClass`` does not have any steps defined it **will** throw ``MockMissingException`` when used. Furthermore - and much more of a 'gotcha' - if an intermediary step (such as ``Log`` or ``Record``) was added without a further one **this will also** throw ``MockMissingException`` when used.

There is of course value to this - it makes the mocks 'fail fast', rather than provide a default value which is then used and might cause issues quite a ways down the line.

However it should probably something you opt in to.

It's also been noted that throwing an exception is exactly the behaviour you get if you let Visual Studio implement your interfaces rather than Mocklis...

**Comment by eredmo** [comment]
The simplest solution to this issue is to add some sort of 'strict mode' property to the ``MocklisClass`` attribute and have that passed to the ``Mocklis.Core.*Mock`` constructors to correctly initialise the ``_nextStep`` field to either Missing (strict mode) or Dummy (lenient mode).

We'd also need to change the virtual method based mocks in lenient mode to:
* set all out and ref parameters to default
* if a return value was requested - return default

...and lastly change the ``Mocklis.Core.*StepWithNext`` to have 'NextStep' set to a 'Dummy' step instead of a 'Missing' step.

**Comment by eredmo** [comment]
Does it make sense to have three "strictness" levels:
* lenient (what should be the default setting): Default to Dummy for mocks and added steps. 
* strict: Default to Missing for mocks, default to Dummy for added steps. (E.g. MyMock.MyMethod.Log() would be the same as MyMock.MyMethod.Log().Dummy())
* very strict (what we currently have in 0.1.13-alpha): Default to Missing for mocks and added steps. (E.g. MyMock.MyMethod.Log() would be the same as MyMock.MyMethod.Log().Missing())

If this makes sense, how should it be encoded in the MocklisClass attribute?
* Two different booleans, 'strict' and 'veryStrict', where veryStrict trumps strict if both are given.
* An enum with the values Lenient, Strict and VeryStrict.
* Independent booleans for mocks and steps.
* Something better I haven't thought about...

**Comment by eredmo** [comment]
There was one key change under the hood for this feature: a missing step now has the NextStep property set to null rather than a 'Missing' step. That means that we can easily distinguish between a mock without a next step and a step without a next step - as their behaviours differ for the 'Strict' strictness - the former throws but the latter doesn't. A 'Clear' method has been added to the mocks to remove the next step in a more controlled fashion.

**Comment by eredmo** [comment]
This also means that if a user adds a "Missing" step it will **always** throw. This feels a lot less confusing than taking strictness into account.

**Comment by ninjasource** [comment]
> Does it make sense to have three "strictness" levels:
>     * lenient (what should be the default setting): Default to Dummy for mocks and added steps.
>     * strict: Default to Missing for mocks, default to Dummy for added steps. 
>     * very strict (what we currently have in 0.1.13-alpha): Default to Missing for mocks and added steps. 

I think it would make more sense to only have lenient and very strict. That way you only need one attribute: [Strict] 
I think that the added complexity of having multiple levels of strictness (and having to decide between them) is not worth the benefits you mention above.

**Comment by eredmo** [comment]
Opened new issue ( #4 ) to discuss this.
