### ISSUE TITLE
Add comment to auto-generated code

### ISSUE THREAD

**Issue by eredmo** [mocklis/mocklis#3]
From off-line discussion with David H:

The code generated by Mocklis should begin with a comment stating that:

> // The code in this class has been auto-generated by a tool.
> // Any changes you make will be overwritten if the code is re-generated.

...or something to that effect...

**Comment by eredmo** [comment]
Went with:
> // The contents of this class were created by the Mocklis code-generator.
> // Any changes you make will be overwritten if the contents are re-generated.

**Comment by ninjasource** [comment]
Sounds good!
